# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d9be05582da715e1318f934bfcf892499e3259642766ad2c89ff28d87731bedb07f3aaa62386d7373caf81640f615bc8dc324a8214e0c6ad3cce5add507f08e

test:
  secret_key_base: 26987c27ae7cb0c355e78e437b8597e142745024b46d934f8b03fa7c86f564dc8981d1719745c61ee0f586fe64d5427e3429d8ac23b3e887e1af023676f916ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
